version: '3.8'

services:
  # PostgreSQL Database for Testing
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todoapp_test
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Backend for Testing
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # Database Configuration
      POSTGRES_DB: todoapp_test
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      
      # Django Configuration
      DEBUG: "True"
      SECRET_KEY: "test-secret-key-for-ci-cd-only"
      
      # Test Environment Flag
      TESTING: "True"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/todos/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend for Testing
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      # API Configuration
      NEXT_PUBLIC_API_URL: http://backend:8000
      
      # Node Environment
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_test_data:
    driver: local

networks:
  default:
    name: todo-test-network 